### ISSUE TITLE
CitizenFX.Core.UI.Text is no longer available

### ISSUE THREAD

**Issue by Sasino97** [thorium-cfx/mono_v2_get_started#15] opened 2023-06-18 02:17 UTC
### What happened?

`CitizenFX.Core.UI.Text` is no longer available in the new runtime.

### Expected result

For it to be available as `CitizenFX.FiveM.UI.Text`

### Reproduction steps

```bash
N/A
```

### Importancy

Can't use this feature until fixed

### Specific version

6514

### Extra

This one is more important than the Alignment enum; it's safer to manually add that simple enum in my project than to add the entire Text class with its methods that may change in the meanwhile.

**Comment by thorium-cfx** [comment] 2023-06-18 09:53
Thank you for reporting this.

I do need to close this issue as this is not considered a bug but rather a feature request (hence why the template doesn't go well with the report). Please use the "Feature Request" template in the future, for now I took the liberty to make a feature request for this.

Duplicate of #16

**Closed by thorium-cfx** 2023-06-18 09:53 UTC
Labels: bug, triage
