### ISSUE TITLE
Server events handlers invocation error

### ISSUE THREAD

**Issue by Marky-S** [thorium-cfx/mono_v2_get_started#29] opened 2023-10-07 08:14 UTC
### What happened?

Can't handle server event `onResourceStop`

```
[script:core] SCRIPT ERROR: Could not invoke event handler Server.Entry.OnResourceStop
[script:core]   expected: (String)
[script:core]   received: (String)
[script:core]   * Any type in red is not convertible, castable, or simply missing and requires attention.
[script:core] Failed with exception:
[script:core] System.InvalidCastException: Specified cast is not valid.
[script:core]   at Server.Entry.OnResourceStop (System.String resourceName) [0x0001f] in <5d7676cd4bf444b5b52837e7dc51f3c1>:0 
[script:core]   at (wrapper dynamic-method) System.Object.Server.Entry.OnResourceStop(CitizenFX.Core.Remote,object[])
[script:core]   at (wrapper delegate-invoke) <Module>.invoke_object_Remote_object[](CitizenFX.Core.Remote,object[])
[script:core]   at CitizenFX.Core.EventsManager.IncomingEvent (System.String eventName, System.String sourceString, CitizenFX.Core.Binding origin, System.Byte* argsSerialized, System.Int32 serializedSize, System.Object[] args) [0x00049] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore-v2\Interop\EventsManager.cs:35 
```

There is a code:

```csharp
[EventHandler("onResourceStop")]
private static void OnResourceStop(string resourceName)
```

### Expected result

Correct method invocation

### Reproduction steps

```bash
No need.
```

### Importancy

Can't use this feature until fixed

**Comment by thorium-cfx** [comment] 2023-10-07 09:58
Your repro steps are a tad off ;) You also put the (minimal needed) code there to reproduce.

On that note, this works fine:
```cs
[EventHandler("onResourceStop")]
private static void OnResourceStop(string resourceName)
{
	Debug.WriteLine($"Resource {resourceName} stopped");
}
```

Looking at your error, it seems like you're casting something else in your method that's not working out.

Closing this as it seems to be a user error, but we can reopen it when we're able to reproduce it.

**Closed** 2023-10-07 09:59 UTC
