### ISSUE TITLE
CitizenFX.Core.UI.Alignment is no longer available

### ISSUE THREAD

**Issue by Sasino97** [thorium-cfx/mono_v2_get_started#14] opened 2023-06-18 02:09 UTC
### What happened?

The `CitizenFX.Core.UI.Alignment` enum has no direct equivalent in the Mono runtime v2 API.

### Expected result

For it to exist as `CitizenFX.FiveM.UI.Alignment`

### Reproduction steps

```bash
N/A
```

### Importancy

Slight inconvenience

### Specific version

6514

**Comment by thorium-cfx** [comment] 2023-06-18 09:53
Thank you for reporting this.

Just like the other I do need to close this issue as this is not considered a bug but rather a feature request (hence why the template doesn't go well with the report). Please use the "Feature Request" template in the future, for now I took the liberty to make a feature request for this.

Duplicate of #16

**Closed by thorium-cfx** 2023-06-18 09:53 UTC
Labels: bug, triage
